# Docker Compose for Flask Chat Server Development
version: '3.8'

services:
  chat-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: transcribe-chat-dev
    ports:
      - '5000:5000'
    volumes:
      - ./src:/app/src:ro
      - ./static:/app/static:ro
      - ./templates:/app/templates:ro
      - ./.env:/app/.env:ro
      - chat-logs:/app/logs
      - chat-cache:/app/cache
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - FLASK_PORT=5000
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - transcribe-network

  chat-server-prod:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: transcribe-chat-prod
    ports:
      - '5001:5000'
    volumes:
      - ./.env:/app/.env:ro
      - chat-logs:/app/logs
      - chat-cache:/app/cache
    environment:
      - FLASK_ENV=production
      - FLASK_PORT=5000
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - transcribe-network
    profiles:
      - production

volumes:
  chat-logs:
    driver: local
  chat-cache:
    driver: local

networks:
  transcribe-network:
    driver: bridge
