"""
Zilliz Cloud client using native BM25 full-text search for the sparse side.

Milvus/Zilliz generates the sparse vector from raw text server-side via a BM25
Function attached to the `text` field, and hybrid search is performed with
pymilvus's built-in AnnSearchRequest + RRFRanker.
"""

import numpy as np
from typing import List, Dict, Any
from pymilvus import (
    connections,
    Collection,
    FieldSchema,
    CollectionSchema,
    DataType,
    Function,
    FunctionType,
    AnnSearchRequest,
    RRFRanker,
)

from models.conversation_chunk import ConversationChunk, SearchResult

# lindera (Rust MeCab-compatible tokenizer, ipadic dictionary) is Milvus's
# actual Japanese-capable analyzer - "standard" only splits on punctuation
# (a whole sentence becomes one token) and "chinese"/jieba mis-segments
# Japanese inflected forms. Verified with MilvusClient.run_analyzer:
#   lindera/ipadic -> ['仕事','が','楽しく','なっ','た','。','東京','で','Kubernetes','を','学ぶ','。']
# The stop filter below drops particles/punctuation; there is no built-in
# Japanese stopword list ("_japanese_stopwords_" is silently ignored), so an
# explicit list is given.
JAPANESE_STOPWORDS = [
    "を", "が", "に", "で", "と", "の", "は", "も", "や", "へ", "から", "まで",
    "より", "な", "だ", "です", "ます", "た", "。", "、",
]

DEFAULT_JAPANESE_ANALYZER_PARAMS = {
    "tokenizer": {"type": "lindera", "dict_kind": "ipadic"},
    "filter": [
        "lowercase",
        {"type": "stop", "stop_words": JAPANESE_STOPWORDS},
    ],
}


class ZillizBM25Client:
    """Zilliz Cloud client using native BM25 for sparse (full-text) search."""

    def __init__(
        self,
        uri: str,
        token: str,
        collection_name: str = "conversation_chunks_bm25",
        analyzer_params: Dict[str, Any] = None,
    ):
        """
        Args:
            uri: Zilliz Cloud URI
            token: Zilliz Cloud token
            collection_name: Collection name
            analyzer_params: Milvus analyzer config used to tokenize `text` for BM25.
                              Defaults to a lindera/ipadic tokenizer with a Japanese
                              particle/punctuation stop-word filter (see
                              DEFAULT_JAPANESE_ANALYZER_PARAMS above).
        """
        self.uri = uri
        self.token = token
        self.collection_name = collection_name
        self.analyzer_params = analyzer_params or DEFAULT_JAPANESE_ANALYZER_PARAMS
        self.collection = None

        self._connect()
        self._setup_collection()

    def _connect(self):
        try:
            connections.connect(alias="default", uri=self.uri, token=self.token)
            print("✅ Connected to Zilliz Cloud (BM25 client)")
        except Exception as e:
            print(f"❌ Zilliz Cloud connection error: {e}")
            raise

    def _setup_collection(self):
        from pymilvus import utility

        try:
            if not utility.has_collection(self.collection_name):
                print(
                    f"⚠️ Collection '{self.collection_name}' does not exist. Creating it..."
                )
                self._create_collection()
            else:
                self.collection = Collection(self.collection_name)
                print(f"✅ Connected to existing collection '{self.collection_name}'")

            try:
                self.collection.load()
                print("✅ Collection loaded successfully")
            except Exception as load_err:
                if "already loaded" in str(load_err).lower():
                    print("✅ Collection already loaded")
                else:
                    print(f"⚠️ Collection load warning: {load_err}")

        except Exception as e:
            print(f"❌ Collection setup error: {e}")
            raise

    def _create_collection(self):
        """Create collection with dense_vector + BM25-backed sparse_vector."""
        try:
            print(
                f"🔨 Creating collection '{self.collection_name}' with native BM25 schema..."
            )

            fields = [
                FieldSchema(
                    name="id", dtype=DataType.VARCHAR, max_length=500, is_primary=True
                ),
                FieldSchema(
                    name="dense_vector", dtype=DataType.FLOAT_VECTOR, dim=768
                ),  # SentenceTransformer embedding dimension
                FieldSchema(
                    name="text",
                    dtype=DataType.VARCHAR,
                    max_length=2000,
                    enable_analyzer=True,
                    analyzer_params=self.analyzer_params,
                ),
                FieldSchema(
                    name="sparse_vector", dtype=DataType.SPARSE_FLOAT_VECTOR
                ),  # Auto-generated by the BM25 function below - never insert manually
                FieldSchema(name="speaker", dtype=DataType.VARCHAR, max_length=500),
                FieldSchema(name="timestamp", dtype=DataType.VARCHAR, max_length=50),
                FieldSchema(name="chunk_index", dtype=DataType.INT64),
                FieldSchema(name="original_length", dtype=DataType.INT64),
                FieldSchema(name="file_name", dtype=DataType.VARCHAR, max_length=500),
                FieldSchema(name="title", dtype=DataType.VARCHAR, max_length=500),
            ]

            bm25_function = Function(
                name="text_bm25_emb",
                input_field_names=["text"],
                output_field_names=["sparse_vector"],
                function_type=FunctionType.BM25,
            )

            schema = CollectionSchema(
                fields=fields,
                description="Conversation chunks with dense vectors + native BM25 sparse vectors",
                functions=[bm25_function],
            )

            self.collection = Collection(
                name=self.collection_name, schema=schema, using="default"
            )

            print(f"✅ Collection '{self.collection_name}' created successfully")
            print("📋 Schema:")
            print("   - id: Primary key (VARCHAR)")
            print("   - dense_vector: SentenceTransformer embeddings (768D)")
            print(f"   - text: analyzed text (analyzer={self.analyzer_params}) -> BM25 function")
            print("   - sparse_vector: auto-generated by BM25 function (do not insert manually)")

            self._create_indexes_for_empty_collection()

        except Exception as e:
            print(f"❌ Collection creation error: {e}")
            raise

    def _create_indexes_for_empty_collection(self):
        """Create indexes for empty collection (called during setup)"""
        try:
            print("🔧 Creating initial indexes for empty collection...")

            dense_index_params = {
                "metric_type": "IP",
                "index_type": "FLAT",
            }
            self.collection.create_index("dense_vector", dense_index_params)
            print("   ✅ Dense vector index created (FLAT/IP)")

            sparse_index_params = {
                "index_type": "SPARSE_INVERTED_INDEX",
                "metric_type": "BM25",
            }
            self.collection.create_index("sparse_vector", sparse_index_params)
            print("   ✅ Sparse vector index created (SPARSE_INVERTED_INDEX/BM25)")

            self.collection.load()
            print("✅ Created initial indexes and loaded collection")

        except Exception as e:
            print(f"❌ Initial index creation error: {e}")
            print("💡 Indexes can be created later when data is inserted")

    def insert_data(self, chunks: List[ConversationChunk], dense_embeddings: np.ndarray):
        """
        Insert chunks with dense vectors. The sparse_vector column is a function
        output field - Milvus derives it from `text` automatically and it must
        NOT be included in the insert payload.
        """
        data = [
            [chunk.id for chunk in chunks],
            dense_embeddings.tolist(),
            [chunk.text for chunk in chunks],
            [chunk.speaker for chunk in chunks],
            [chunk.timestamp for chunk in chunks],
            [chunk.chunk_index for chunk in chunks],
            [chunk.original_length for chunk in chunks],
            [chunk.file_name for chunk in chunks],
            [chunk.title for chunk in chunks],
        ]

        try:
            self.collection.insert(data)
            self.collection.flush()
            print(f"✅ Inserted {len(chunks)} chunks (BM25 sparse vector auto-generated)")
        except Exception as e:
            print(f"❌ Data insertion error: {e}")
            raise

    def hybrid_search(
        self,
        dense_query: np.ndarray,
        query_text: str,
        limit: int = 5,
        rerank_k: int = 100,
    ) -> List[SearchResult]:
        """
        Native Milvus hybrid search: dense ANN (IP) + BM25 full-text search on
        raw query text, fused server-side via Reciprocal Rank Fusion.
        """
        try:
            if self.collection is None:
                print("❌ Hybrid search error: collection is not initialized")
                return []

            out_fields = ["text", "speaker", "timestamp", "file_name", "title"]

            dense_req = AnnSearchRequest(
                data=dense_query,
                anns_field="dense_vector",
                param={"metric_type": "IP", "params": {"nprobe": 16}},
                limit=rerank_k,
            )
            sparse_req = AnnSearchRequest(
                data=[query_text],
                anns_field="sparse_vector",
                param={"metric_type": "BM25", "params": {}},
                limit=rerank_k,
            )

            results = self.collection.hybrid_search(
                reqs=[dense_req, sparse_req],
                rerank=RRFRanker(),
                limit=limit,
                output_fields=out_fields,
            )

            return self._to_search_results(results, "hybrid_bm25")

        except Exception as e:
            print(f"❌ BM25 hybrid search error: {e}")
            return []

    def bm25_search(self, query_text: str, limit: int = 5) -> List[SearchResult]:
        """Full-text BM25 search only (no dense component)."""
        try:
            if self.collection is None:
                print("❌ BM25 search error: collection is not initialized")
                return []

            results = self.collection.search(
                data=[query_text],
                anns_field="sparse_vector",
                param={"metric_type": "BM25", "params": {}},
                limit=limit,
                output_fields=["text", "speaker", "timestamp", "file_name", "title"],
            )
            return self._to_search_results(results, "bm25")

        except Exception as e:
            print(f"❌ BM25 search error: {e}")
            return []

    def _to_search_results(self, results, search_type: str) -> List[SearchResult]:
        search_results = []
        if not results or not results[0]:
            return search_results
        for hit in results[0]:
            search_results.append(
                SearchResult(
                    text=hit.entity.get("text", ""),
                    speaker=hit.entity.get("speaker", ""),
                    timestamp=hit.entity.get("timestamp", ""),
                    file_name=hit.entity.get("file_name", ""),
                    score=float(hit.score),
                    similarity=float(hit.score),
                    search_type=search_type,
                    title=hit.entity.get("title", ""),
                )
            )
        return search_results

    def get_collection_stats(self) -> Dict[str, Any]:
        """Get collection statistics"""
        try:
            try:
                num_entities = self.collection.num_entities
            except Exception:
                num_entities = None

            return {
                "collection_name": self.collection_name,
                "num_entities": num_entities,
            }
        except Exception as e:
            print(f"❌ Error getting collection stats: {e}")
            return {}
